### ISSUE TITLE
Loading Neighbor Levels is Slow

### ISSUE THREAD

**Issue by tgreener** [Trouv/bevy_ecs_ldtk#101]
I have created an RPG-esque map where the player can move between levels. I am using a 2D free map world in LDtk, and am using `LevelSelection::Uid` with  `LevelSpawnBehavior::UseWorldTranslation { load_level_neighbors: true }`. When my player entity moves into a neighboring level, I select it, causing its neighbors to load.

For example, let's say that the world is something like this:
```
A - B 
|\- F
D - E
``` 

When I move to 'A' or 'D' from any other level, there is a noticeable stutter, which becomes larger the more neighbors a level has. In the console, it shows `INFO bevy_ecs_tilemap::layer: Updating tile cache.` In the example, 'A' would have the worst stutter because it has 3 neighbors.

Moving into edge levels ('B' or 'E)' does not have any noticeable stutter, and the updating tile cache message is not printed to the terminal.

**Comment by tgreener** [comment]
Could be related to https://github.com/Trouv/bevy_ecs_ldtk/issues/87, as I have my ldtk project organized into quite a few layers that use the same texture atlas (for z layering and convenience)

**Comment by Trouv** [comment]
Yeah, I haven't done testing on simultaneously spawning more than 2 or 3 levels.

Is there any chance that your game has any collision logic, like with physics? Since the global transforms of all the level's entities aren't updated until one update *after* they have spawned, newly-spawned entities will just have global transforms of 0 for one update, and all the level's entities will be on top of each other temporarily. This will create tons of collisions, if that's something you need to worry about. For that reason, the `platformer` example pauses all physics while levels are spawning: https://github.com/Trouv/bevy_ecs_ldtk/blob/main/examples/platformer/systems.rs#L22

I'm also curious if you see any improvements by depending on the `main` branch of this plugin. There haven't been many changes since the last release, but one was a performance-related bug fix: https://github.com/Trouv/bevy_ecs_ldtk/pull/98

Like I mentioned earlier, I haven't tested spawning more than 2 or 3 levels at once, so I wouldn't be surprised if neither of these things fix the issue and that the spawning is just slow.

**Comment by tgreener** [comment]
The collision thing could be the culprit. I'll look at the platformer example and see if I can resolve this.

**Comment by tgreener** [comment]
Yeah, the collisions were the problem. You're a very clever person ;3
