### ISSUE TITLE
Improving ldtk json documentation

### ISSUE THREAD

**Issue by holly-hacker** [Trouv/bevy_ecs_ldtk#141]
While using bevy_ecs_ldtk, I've found the automatically generated documentation for the json data to be fairly lacking. I noticed a comment at the top of `src/ldtk/mod.rs` saying it is automatically generated and shouldn't be edited manually because it makes maintaining it harder.

Are there any plans to change this in the future to allow clarifying the automatically generated documentation, or should this be contributed upstream to ldtk itself?

**Comment by Trouv** [comment]
Yeah, the majority of the rust serde code is generated by the ldtk project itself using Quicktype. If the documentation clarifications are not specific to bevy or rust, they should be contributed upstream somehow. I'm not exactly sure how it works but I believe that sort of contribution will also affect the docs for the ldtk loaders of other languages.

If it is rust/bevy specific, we can contribute it here, but as you pointed out - I'm picky about the sort of changes I make to that module since I have to re-make those changes every time ldtk releases a new version that changes the API (thus generating a new module for ldtk types from quicktype). It'd be nice to have a way to remake those changes automatically, then I would be more willing to accept any improvements.

**Comment by holly-hacker** [comment]
I see, that makes sense. Thanks anyway!
