### ISSUE TITLE
Translation of entity doens't match up with their displayed position 

### ISSUE THREAD

**Issue by tsalkenov** [Trouv/bevy_ecs_ldtk#226]
When i try to center my camera using translation of player entity created from ldtk_entity. The translation i get has -800 offset by x and +800 offset by y from player sprite

**Comment by Trouv** [comment]
Could it be a Transform vs GlobalTransform issue? LdtkEntities are children of their level by default and if the level entity or world entity's transforms aren't both 0 then the LdtkEntity will have a global transform different from its transform

**Comment by tsalkenov** [comment]
Oooh yeah i needed to use global transform. But i use the same camera and level selection updater as in the platformer example but it only works properly when Transform of player is being replaced by GlobalTransform why does example work with local one

**Comment by Trouv** [comment]
Well, in the platformer example the player is "Worldly", meaning that it's a child of the world rather than the level. The world transform actually does have a 0 transform there, even though the levels don't. It could probably be updated to work with global transforms to avoid confusing users anyway

**Comment by tsalkenov** [comment]
Thanks for explanation and your work
