### ISSUE TITLE
Access tile data

### ISSUE THREAD

**Issue by jcornaz** [Trouv/bevy_ecs_ldtk#52]
Hi, 

Ldtk makes it possible to link data to tiles of a tile-set (either arbitrary text or enum-based)

It would be nice if there was a `TileData`(or equivalent) component inserted on tiles that have data defined so that we could query them and have logic based on the data we defined in ldtk.

**Comment by Trouv** [comment]
Thanks for the suggestion! To be honest, I'm a little bit hesitant about tileset data. To me, it seems like the use cases for it are usually better solved with intgrid/auto-tile layers. If it's not a commonly-used feature then I don't want it to add too much maintenance overhead to the plugin.

However, I'm open minded about this and am sure I can be convinced that the feature is worthwhile. Especially if there's a compelling use case that is better solved with tile data than intgrid/auto-tile layers, or if enough people express interest in the feature (thumbs up the issue!). I'm open to PRs as well, of course.

For the time being, the tile data can be accessed with the current plugin using `Assets<LdtkAsset>` and navigating to the tileset definition, but it's definitely not very ergonomic.

**Comment by jcornaz** [comment]
Personally, I use them both together int-grid and tile data. Here is a use-case for combining both:

Let's say it is a top-down rpg game, and I have a "grass" tileset. Most of the tiles are variations of grass pattern, and some are bushes and berries, stuff like that. I mark the berries with special data because the player may pick them up.

Then with the grid layer, I put all the different grass ground in the same ground value. And I use the int-grid rules to let ldtk randomly choose between the different grass tiles, bushes and berries (with a probability and perlin-noise pattern).

With this example, I cannot rely solely on the int-grid values because bushes, berries and grass have all the same value. But the tile data is different :-)

Anyway, this is of course a nice-to-have. I can either Manually access the ldtk asset, or manually spawn the bushes instead of letting ldtk randomly generate them.

**Comment by Trouv** [comment]
That makes a lot of sense. I'm on board now. It's not super high priority but I think it would be a good change, and inserting that data into a component is a very reasonable way to implement it.

**Comment by Trouv** [comment]
Looking into this a bit, and it's pretty difficult to weigh against the performance costs right now.

I'd like to add a component with the metadata ONLY to tile entities that have metadata, because I doubt most users would have tile data on all, or even most of the tiles in their tileset. So, storing an empty metadata component on most tile entities would be pretty wasteful memory-wise. It would also be annoying/slow to filter through everytime you needed to query for that metadata.

However, this is difficult (maybe impossible) to accomplish with bevy_ecs_tilemap's `LayerBuilder::new_batch` method, which is how the plugin currently spawns tile and autotile layers. It's difficult because a `LayerBuilder` is generic over a particular `Bundle` and using this method you can only spawn entities with that bundle, no adding components on top of them. This is why int grid layers (even those with autotile rules) do not use `LayerBuilder::new_batch` and instead set all the tiles individually, so `Transform` and any `LdtkIntGrid` can be added to these entities as well. The batch method is preferred though because it is much faster, apparently.

So, either there's a memory/querying performance hit, or there's a level spawning performance hit. I think I'd take the latter over the former since it will probably be less annoying for users, but maybe under an opt-in feature called "metadata" or something.

**Comment by Trouv** [comment]
Working on this again. I've made some decisions:
1. *not* going to put this behind a feature
2. Going to only add the metadata components to the tiles that have metadata
3. Planning to add this in `0.3`

I figured out that I could pretty easily tell whether or not a layer was going to have metadata on it at all, and make it use `new_batch` when it doesn't. This way, if users aren't using metadata in their ldtk file, they're basically "opting out" of the performance hit like they would be when excluding a feature. Furthermore, I doubt many people would be using tile metadata in LDtk without also wanting to use it in bevy. So, putting it behind a feature would be pretty pointless.

Also, I think my performance concerns were a bit ridiculous. After implementing a lot of the logic and trying it on the bigger examples, using the slower `LayerBuilder` functions has no discernible affect.
