### ISSUE TITLE
AutoLayerRuleGroup does not have field 'collapsed'

### ISSUE THREAD

**Issue by unlink2** [Trouv/bevy_ecs_ldtk#69]
I've been working with auto layer rules and I've noticed that the field ['collapsed'](https://github.com/Trouv/bevy_ecs_ldtk/blob/460fdd617405bca7cd95d65d47e73e3620dbbdac/src/ldtk/mod.rs#L493-L494) is not actually present in autoRuleGroups.
This causes the map load to fail. 

Here is an example of what my autoRuleGroup actually looks like: 

```json
"autoRuleGroups": [
    {
      "uid": 28,
      "name": "Test",
      "active": true,
      "isOptional": false,
      "rules": []
    }
  ]
```
I'm rather new to LDTk, but if I understand  the documentation correctly auto tile rules are not meant to be used in-engine, and the exact JSON format is not documented so this might be down to a change in recent versions.

I am using LDTk 1.1.1.

Thanks for the awesome library :)

**Comment by Trouv** [comment]
Yeah, that's probably because of your LDtk version. The most recent release of this plugin, 0.2, only supports up to LDtk 0.9. 1.0+ support is being worked on here #68, and is pretty usable in its current state if you just want to point your dependency to the `ldtk-1.0` branch. I'm going to a cut a new release of this plugin with LDtk 1.0+ support after bevy 0.7 and bevy_ecs_tilemap 0.6 are released, which is right around the corner.

**Comment by unlink2** [comment]
Right, my bad I did not look at the correct branch. Thank you for the quick response!
