### ISSUE TITLE
When change `LevelSpawnBehavior::UseZeroTranslation` to `LevelSpawnBehavior:: UseWorldTranslation{load_level_neighbors: true,}` all collision positions shifting

### ISSUE THREAD

**Issue by MadMed677** [Trouv/bevy_ecs_ldtk#89]
Hi. During your example `platformer` I tried to make the same logic for my own game. But when I've changed `LevelSpawnBehaviour::UseZeroTranslation` to 

```rust
LevelSpawnBehavior::{
  load_level_neighbors: true,
}
```

Before that, all collisions work fine, and the game is 100% legit. But after changing the config all collisions took the wrong position and were placed at the same place as it was for `UseZeroTranslation`.
The same problem with the `Ladder` collision. When I change the config all collisions for entities also shift.

Do you face that problem during your `platformer` example? If yes, how to deal with it?

**Comment by Trouv** [comment]
Just to make sure, are you doing this:
```rust
app.insert_resource(LdtkSettings {
        level_spawn_behavior: LevelSpawnBehavior::UseWorldTranslation {
            load_level_neighbors: true,
        },
        ..default()
    })
```

With the `LdtkSettings` as the actual resource, and specifying the `UseWorldTranslation` variant?

**Comment by MadMed677** [comment]
Yep, sorry forgot to copy all the code snapshot.

**Comment by Trouv** [comment]
Took a peak at your project. You're using rapier right?

It looks like rapier ignores `GlobalTransform`s and only pays attention to `Transform`s, unfortunately. So, the "location" of the rigid bodies won't inherit the translation of their parent level. I imagine this is unintended: https://github.com/dimforge/bevy_rapier/issues/172

For now, you can do the global transformation logic yourself. Instead of giving the wall collisions a global transform and a parent, you can divide the transform you intend to give it by the transform of the level before inserting it. Though, with this solution, you won't get collision despawning for free when levels are "unloaded" recursively. You'll need a new system for that, maybe one that listens for `LevelEvent::Despawned`.

**Comment by MadMed677** [comment]
Oh, got it. Thanks a lot for your job ❤️

**Comment by MadMed677** [comment]
But the question is: "How to take transform for the specific level"?

**Comment by Trouv** [comment]
You could add it to the `level_query` in the `spawn_wall_collisions` system. In general, the level entities have a `Handle<LdtkLevel>` component. Maybe consider getting its `GlobalTransform` instead of its `Transform`, that might be more correct.

**Comment by MadMed677** [comment]
After [bevy_rapier2d@0.14](https://github.com/dimforge/bevy_rapier/pull/181) release everything works correctly because bevy_rapier now works with `GlobalTransform` and `Transform`. Behaviour is the same as with `heron`
