### ISSUE TITLE
Best way to get tile entity from its GridCoords?

### ISSUE THREAD

**Issue by mystal** [Trouv/bevy_ecs_ldtk#93]
I wasn't sure the best place to ask this question. I tried on the Bevy Discord's \#help channel, but got no replies, so here I am!

Is there a way to get a tile from `GridCoord`s? I'm making a grid-based game and am simply using certain tiles as blocking terrain. So I wanted to be able to look up a tile from a coordinate and check what type it is to determine whether it blocks movement or not.

My hacky workaround was going to be to iterate all the tiles and store the ones with blocking collision in a HashMap resource. That way I can just check the resource when the player tries to move.

**Comment by Trouv** [comment]
Sorry, I've been a little absent on the discord lately, I'll try to be more attentive again.

Are you flagging the collision tiles with a collision component of some sort? You can always just have a `collision_query: Query<GridCoords, With<MyCollisionComponent>>` in your collision detection system, and check that with `collision_query.iter().find(|g| g == grid_coords)`, but that's basically just iterating through it like you're suggesting.

Another option that acts more like a lookup is to use some underlying `bevy_ecs_tilemap` stuff. You can use its `MapQuery::get_tile_entity`to get tile entities given a `TilePos`. A `TilePos` is just `bevy_ecs_tilemap`s tile coordinate, we provide `GridCoords` conversions for it. I wouldn't recommend this though, since you'd need an additional query to check if it's a collision tile or not, and you'll also need to know what the level's `MapId` and `LayerId` are.

Building a HashMap resource and storing it in there is a good idea, that's probably what I would do. That way you only have to calculate it once per level. I don't think it's that hacky. Though, I'd wrap the hashmap in a new type to give stronger type meaning to it. If collisions will be changing for some reason it may be better to calculate it dynamically when the player moves, but otherwise I think that's the strat.

**Comment by mystal** [comment]
> Are you flagging the collision tiles with a collision component of some sort?
I tagged them with an enum in LDTK.

> Another option that acts more like a lookup is to use some underlying `bevy_ecs_tilemap` stuff.
Yeah, I was wondering if the underlying API had this kind of stuff. Good to know it does, but it does sound complicated.

> Building a HashMap resource and storing it in there is a good idea, that's probably what I would do.
This is what I ended up doing! It's pretty straightforward and I could query for tiles using `Query<(&GridCoords, &TileEnumTags)>`.

Thanks for the reply! You've definitely answered my question. I'll close this out.
