### ISSUE TITLE
Is it possible to set the `z` transform for an auto tile layer?

### ISSUE THREAD

**Issue by maccesch** [Trouv/bevy_ecs_ldtk#95]

**Comment by Trouv** [comment]
It's not impossible, but there's not a good built-in solution for it. You'll need to interface with `bevy_ecs_tilemap` APIs, and there won't be a great dynamic way to determine which layer is which.

All Tile/AutoTile layer entities have a `bevy_ecs_tilemap::Layer` component, so you can query for those and set their transforms as you please. For now, the best way to differentiate between these layers is their z-value, unfortunately. The z values will be whole numbers, with the background layers being lower and the foreground layers being higher values. For simple situations, the z value generally corresponds with the layer "number" in LDtk (1-indexed if you're rendering background colors (default), 0-indexed if you've turned that off through `LdtkSettings`). There are some things that can complicate this though, like background images, or AutoTile layers with colliding tiles (requiring them to take up multiple `bevy_ecs_tilemap` layers instead of one).

Then once you've figured out what layer you're dealing with, you can set the z-value however you like. However, if you're trying to change render-ordering between different layers or something like that, I'm not 100% sure you'll be able to accomplish this. `bevy_ecs_tilemap` has an additional, private field for layers called the `layer_id`, and I think it may be used for rendering order.

It'd probably be a good idea to add some ldtk-related layer metadata to layer entities in a future release.

**Comment by maccesch** [comment]
Thanks for this detailed answer!
